In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

In [2]:
df=pd.read_csv(r"C:\Users\THAJIN T\Downloads\crop_production.csv\crop_production.csv")
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [3]:
df.isnull().sum()

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

In [4]:
df.dropna(inplace=True)

In [5]:
df.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [6]:
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [7]:
ob1=LabelEncoder()
ob2=LabelEncoder()
ob3=LabelEncoder()
ob4=LabelEncoder()

In [8]:
df['State_Name']=ob1.fit_transform(df['State_Name'])
df['District_Name']=ob2.fit_transform(df['District_Name'])
df['Season']=ob3.fit_transform(df['Season'])
df['Crop']=ob4.fit_transform(df['Crop'])

In [9]:
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,0,427,2000,1,2,1254.0,2000.0
1,0,427,2000,1,74,2.0,1.0
2,0,427,2000,1,95,102.0,321.0
3,0,427,2000,4,7,176.0,641.0
4,0,427,2000,4,22,720.0,165.0
...,...,...,...,...,...,...,...
246086,32,471,2014,3,95,306.0,801.0
246087,32,471,2014,3,102,627.0,463.0
246088,32,471,2014,4,106,324.0,16250.0
246089,32,471,2014,5,95,279151.0,597899.0
246090,32,471,2014,5,102,175.0,88.0

In [10]:
x=df.drop(['Production'],axis=1)
x

        State_Name  District_Name  Crop_Year  Season  Crop      Area
0                0            427       2000       1     2    1254.0
1                0            427       2000       1    74       2.0
2                0            427       2000       1    95     102.0
3                0            427       2000       4     7     176.0
4                0            427       2000       4    22     720.0
...            ...            ...        ...     ...   ...       ...
246086          32            471       2014       3    95     306.0
246087          32            471       2014       3   102     627.0
246088          32            471       2014       4   106     324.0
246089          32            471       2014       5    95  279151.0
246090          32            471       2014       5   102     175.0

[242361 rows x 6 columns]

In [11]:
y=df.Production
y

0           2000.0
1              1.0
2            321.0
3            641.0
4            165.0
            ...
246086       801.0
246087       463.0
246088     16250.0
246089    597899.0
246090        88.0
Name: Production, Length: 242361, dtype: float64

In [12]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)
xtrain

        State_Name  District_Name  Crop_Year  Season  Crop      Area
227784          30            528       2002       2    41     674.0
73466           11            545       2007       1    43      36.0
148845          22             76       2004       4    32     361.0
209150          30            182       1999       1    43      24.0
30541            4            102       2000       4   106     330.0
...            ...            ...        ...     ...   ...       ...
122353          16            536       2003       1   102    5027.0
105927          16            115       2001       2   119  135877.0
134528          17            474       1998       1    65     400.0
149528          22            129       1998       5    45    3900.0
124463          16            609       2004       1     3    5259.0

[169652 rows x 6 columns]

In [13]:
ytrain

227784       614.0
73466         37.0
148845       176.0
209150        28.0
30541       7617.0
            ...
122353      3103.0
105927    238501.0
134528       100.0
149528      1470.0
124463      2831.0
Name: Production, Length: 169652, dtype: float64

In [14]:
X=np.asarray(xtrain)
Y=np.asarray(ytrain)

In [15]:
model=RandomForestRegressor()
parameters={'n_estimators':[100,150,200,125,250,300]}

In [16]:
forest=GridSearchCV(model,parameters,cv=5)
forest.fit(X,Y)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'n_estimators': [100, 150, 200, 125, 250, 300]})

In [17]:
best_parameters=forest.best_params_
print(best_parameters)

{'n_estimators': 200}

In [18]:
highest_accuracy=forest.best_score_
print(highest_accuracy)

0.939264897573566

In [19]:
final=RandomForestRegressor(n_estimators=200)
final.fit(xtrain,ytrain)

RandomForestRegressor(n_estimators=200)

In [21]:
pred=final.predict(xtest)
pred

array([5.10607910e+03, 7.39249000e+02, 1.01300500e+02, ...,
       1.09960000e+02, 8.62909000e+03, 1.07344611e+05], shape=(72709,))

In [22]:
final.score(xtrain,ytrain)

0.9923550082547148

In [23]:
final.score(xtest,ytest)

0.8421582918099052

In [25]:
df.iloc[181794]

State_Name         27.0
District_Name     508.0
Crop_Year        2012.0
Season              1.0
Crop              107.0
Area               48.0
Production         99.0
Name: 185142, dtype: float64

In [26]:
final.predict([[27,508,2012,1,107,48]])

C:\Users\THAJIN T\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([87.185])

In [27]:
score=r2_score(ytest,pred)
score

0.8421582918099052